# Generated by Django 4.2.7 on 2025-07-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_user_managers_remove_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar_color',
        ),
        migrations.RemoveField(
            model_name='user',
            name='avatar_pattern',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_accessory',
            field=models.CharField(blank=True, choices=[('scarf', 'Scarf'), ('earrings', 'Earrings'), ('glasses', 'Glasses')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_generation_in_progress',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_headwear',
            field=models.CharField(blank=True, choices=[('bandana', 'Bandana'), ('crown', 'Crown'), ('cap', 'Cap')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=200000, max_digits=12),
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
