# Generated by Django 4.2.7 on 2025-07-17 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_remove_user_avatar_color_remove_user_avatar_pattern_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_favorite_color',
            field=models.CharField(blank=True, choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('purple', 'Purple'), ('orange', 'Orange'), ('pink', 'Pink'), ('black', 'Black'), ('white', 'White'), ('brown', 'Brown')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
    ]
