# Generated by Django 4.2.7 on 2025-07-17 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_user_avatar_favorite_color_user_avatar_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamestatistics',
            name='honeycomb_eliminations',
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting for Players'), ('lobby', 'In Lobby'), ('quiz', 'Quiz Stage'), ('red_light', 'Red Light Green Light'), ('freedom_room', 'Freedom Room'), ('finished', 'Finished')], default='waiting', max_length=20),
        ),
        migrations.DeleteModel(
            name='HoneycombAttempt',
        ),
        migrations.DeleteModel(
            name='HoneycombShape',
        ),
    ]
